// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: internal.proto

package internalv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GoQuorumInternal_Replicate_FullMethodName           = "/goquorum.internal.v1.GoQuorumInternal/Replicate"
	GoQuorumInternal_Read_FullMethodName                = "/goquorum.internal.v1.GoQuorumInternal/Read"
	GoQuorumInternal_Heartbeat_FullMethodName           = "/goquorum.internal.v1.GoQuorumInternal/Heartbeat"
	GoQuorumInternal_AntiEntropyExchange_FullMethodName = "/goquorum.internal.v1.GoQuorumInternal/AntiEntropyExchange"
	GoQuorumInternal_GetMerkleRoot_FullMethodName       = "/goquorum.internal.v1.GoQuorumInternal/GetMerkleRoot"
)

// GoQuorumInternalClient is the client API for GoQuorumInternal service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GoQuorumInternalClient interface {
	// Replicate is used by coordinator to replicate writes to other nodes
	Replicate(ctx context.Context, in *ReplicateRequest, opts ...grpc.CallOption) (*ReplicateResponse, error)
	// Read is used by coordinator to read from replicas
	Read(ctx context.Context, in *InternalReadRequest, opts ...grpc.CallOption) (*InternalReadResponse, error)
	// Heartbeat is used for failure detection between nodes
	Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error)
	// AntiEntropyExchange is used for background replica synchronization
	AntiEntropyExchange(ctx context.Context, in *AntiEntropyRequest, opts ...grpc.CallOption) (*AntiEntropyResponse, error)
	// GetMerkleRoot returns the Merkle tree root hash
	GetMerkleRoot(ctx context.Context, in *GetMerkleRootRequest, opts ...grpc.CallOption) (*GetMerkleRootResponse, error)
}

type goQuorumInternalClient struct {
	cc grpc.ClientConnInterface
}

func NewGoQuorumInternalClient(cc grpc.ClientConnInterface) GoQuorumInternalClient {
	return &goQuorumInternalClient{cc}
}

func (c *goQuorumInternalClient) Replicate(ctx context.Context, in *ReplicateRequest, opts ...grpc.CallOption) (*ReplicateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReplicateResponse)
	err := c.cc.Invoke(ctx, GoQuorumInternal_Replicate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goQuorumInternalClient) Read(ctx context.Context, in *InternalReadRequest, opts ...grpc.CallOption) (*InternalReadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InternalReadResponse)
	err := c.cc.Invoke(ctx, GoQuorumInternal_Read_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goQuorumInternalClient) Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HeartbeatResponse)
	err := c.cc.Invoke(ctx, GoQuorumInternal_Heartbeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goQuorumInternalClient) AntiEntropyExchange(ctx context.Context, in *AntiEntropyRequest, opts ...grpc.CallOption) (*AntiEntropyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AntiEntropyResponse)
	err := c.cc.Invoke(ctx, GoQuorumInternal_AntiEntropyExchange_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goQuorumInternalClient) GetMerkleRoot(ctx context.Context, in *GetMerkleRootRequest, opts ...grpc.CallOption) (*GetMerkleRootResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMerkleRootResponse)
	err := c.cc.Invoke(ctx, GoQuorumInternal_GetMerkleRoot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GoQuorumInternalServer is the server API for GoQuorumInternal service.
// All implementations must embed UnimplementedGoQuorumInternalServer
// for forward compatibility.
type GoQuorumInternalServer interface {
	// Replicate is used by coordinator to replicate writes to other nodes
	Replicate(context.Context, *ReplicateRequest) (*ReplicateResponse, error)
	// Read is used by coordinator to read from replicas
	Read(context.Context, *InternalReadRequest) (*InternalReadResponse, error)
	// Heartbeat is used for failure detection between nodes
	Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error)
	// AntiEntropyExchange is used for background replica synchronization
	AntiEntropyExchange(context.Context, *AntiEntropyRequest) (*AntiEntropyResponse, error)
	// GetMerkleRoot returns the Merkle tree root hash
	GetMerkleRoot(context.Context, *GetMerkleRootRequest) (*GetMerkleRootResponse, error)
	mustEmbedUnimplementedGoQuorumInternalServer()
}

// UnimplementedGoQuorumInternalServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGoQuorumInternalServer struct{}

func (UnimplementedGoQuorumInternalServer) Replicate(context.Context, *ReplicateRequest) (*ReplicateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Replicate not implemented")
}
func (UnimplementedGoQuorumInternalServer) Read(context.Context, *InternalReadRequest) (*InternalReadResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Read not implemented")
}
func (UnimplementedGoQuorumInternalServer) Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Heartbeat not implemented")
}
func (UnimplementedGoQuorumInternalServer) AntiEntropyExchange(context.Context, *AntiEntropyRequest) (*AntiEntropyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AntiEntropyExchange not implemented")
}
func (UnimplementedGoQuorumInternalServer) GetMerkleRoot(context.Context, *GetMerkleRootRequest) (*GetMerkleRootResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMerkleRoot not implemented")
}
func (UnimplementedGoQuorumInternalServer) mustEmbedUnimplementedGoQuorumInternalServer() {}
func (UnimplementedGoQuorumInternalServer) testEmbeddedByValue()                          {}

// UnsafeGoQuorumInternalServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GoQuorumInternalServer will
// result in compilation errors.
type UnsafeGoQuorumInternalServer interface {
	mustEmbedUnimplementedGoQuorumInternalServer()
}

func RegisterGoQuorumInternalServer(s grpc.ServiceRegistrar, srv GoQuorumInternalServer) {
	// If the following call panics, it indicates UnimplementedGoQuorumInternalServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GoQuorumInternal_ServiceDesc, srv)
}

func _GoQuorumInternal_Replicate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReplicateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoQuorumInternalServer).Replicate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GoQuorumInternal_Replicate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoQuorumInternalServer).Replicate(ctx, req.(*ReplicateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoQuorumInternal_Read_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InternalReadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoQuorumInternalServer).Read(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GoQuorumInternal_Read_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoQuorumInternalServer).Read(ctx, req.(*InternalReadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoQuorumInternal_Heartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoQuorumInternalServer).Heartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GoQuorumInternal_Heartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoQuorumInternalServer).Heartbeat(ctx, req.(*HeartbeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoQuorumInternal_AntiEntropyExchange_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AntiEntropyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoQuorumInternalServer).AntiEntropyExchange(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GoQuorumInternal_AntiEntropyExchange_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoQuorumInternalServer).AntiEntropyExchange(ctx, req.(*AntiEntropyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoQuorumInternal_GetMerkleRoot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMerkleRootRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoQuorumInternalServer).GetMerkleRoot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GoQuorumInternal_GetMerkleRoot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoQuorumInternalServer).GetMerkleRoot(ctx, req.(*GetMerkleRootRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GoQuorumInternal_ServiceDesc is the grpc.ServiceDesc for GoQuorumInternal service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GoQuorumInternal_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "goquorum.internal.v1.GoQuorumInternal",
	HandlerType: (*GoQuorumInternalServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Replicate",
			Handler:    _GoQuorumInternal_Replicate_Handler,
		},
		{
			MethodName: "Read",
			Handler:    _GoQuorumInternal_Read_Handler,
		},
		{
			MethodName: "Heartbeat",
			Handler:    _GoQuorumInternal_Heartbeat_Handler,
		},
		{
			MethodName: "AntiEntropyExchange",
			Handler:    _GoQuorumInternal_AntiEntropyExchange_Handler,
		},
		{
			MethodName: "GetMerkleRoot",
			Handler:    _GoQuorumInternal_GetMerkleRoot_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal.proto",
}
