// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: internal.proto

package internalv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NodeStatus int32

const (
	NodeStatus_NODE_UNKNOWN NodeStatus = 0
	NodeStatus_NODE_JOINING NodeStatus = 1
	NodeStatus_NODE_ACTIVE  NodeStatus = 2
	NodeStatus_NODE_LEAVING NodeStatus = 3
)

// Enum value maps for NodeStatus.
var (
	NodeStatus_name = map[int32]string{
		0: "NODE_UNKNOWN",
		1: "NODE_JOINING",
		2: "NODE_ACTIVE",
		3: "NODE_LEAVING",
	}
	NodeStatus_value = map[string]int32{
		"NODE_UNKNOWN": 0,
		"NODE_JOINING": 1,
		"NODE_ACTIVE":  2,
		"NODE_LEAVING": 3,
	}
)

func (x NodeStatus) Enum() *NodeStatus {
	p := new(NodeStatus)
	*p = x
	return p
}

func (x NodeStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NodeStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_proto_enumTypes[0].Descriptor()
}

func (NodeStatus) Type() protoreflect.EnumType {
	return &file_internal_proto_enumTypes[0]
}

func (x NodeStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NodeStatus.Descriptor instead.
func (NodeStatus) EnumDescriptor() ([]byte, []int) {
	return file_internal_proto_rawDescGZIP(), []int{0}
}

type AntiEntropyPhase int32

const (
	AntiEntropyPhase_COMPARE_ROOT  AntiEntropyPhase = 0
	AntiEntropyPhase_COMPARE_LEVEL AntiEntropyPhase = 1
	AntiEntropyPhase_EXCHANGE_KEYS AntiEntropyPhase = 2
)

// Enum value maps for AntiEntropyPhase.
var (
	AntiEntropyPhase_name = map[int32]string{
		0: "COMPARE_ROOT",
		1: "COMPARE_LEVEL",
		2: "EXCHANGE_KEYS",
	}
	AntiEntropyPhase_value = map[string]int32{
		"COMPARE_ROOT":  0,
		"COMPARE_LEVEL": 1,
		"EXCHANGE_KEYS": 2,
	}
)

func (x AntiEntropyPhase) Enum() *AntiEntropyPhase {
	p := new(AntiEntropyPhase)
	*p = x
	return p
}

func (x AntiEntropyPhase) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AntiEntropyPhase) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_proto_enumTypes[1].Descriptor()
}

func (AntiEntropyPhase) Type() protoreflect.EnumType {
	return &file_internal_proto_enumTypes[1]
}

func (x AntiEntropyPhase) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AntiEntropyPhase.Descriptor instead.
func (AntiEntropyPhase) EnumDescriptor() ([]byte, []int) {
	return file_internal_proto_rawDescGZIP(), []int{1}
}

type ReplicateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           []byte                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Sibling       *SiblingData           `protobuf:"bytes,2,opt,name=sibling,proto3" json:"sibling,omitempty"`                                  // Value and context to write
	CoordinatorId string                 `protobuf:"bytes,3,opt,name=coordinator_id,json=coordinatorId,proto3" json:"coordinator_id,omitempty"` // Originating coordinator
	RequestId     int64                  `protobuf:"varint,4,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`            // For deduplication
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplicateRequest) Reset() {
	*x = ReplicateRequest{}
	mi := &file_internal_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplicateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicateRequest) ProtoMessage() {}

func (x *ReplicateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicateRequest.ProtoReflect.Descriptor instead.
func (*ReplicateRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_rawDescGZIP(), []int{0}
}

func (x *ReplicateRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *ReplicateRequest) GetSibling() *SiblingData {
	if x != nil {
		return x.Sibling
	}
	return nil
}

func (x *ReplicateRequest) GetCoordinatorId() string {
	if x != nil {
		return x.CoordinatorId
	}
	return ""
}

func (x *ReplicateRequest) GetRequestId() int64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

type SiblingData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         []byte                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Context       []*ContextEntry        `protobuf:"bytes,2,rep,name=context,proto3" json:"context,omitempty"`
	Tombstone     bool                   `protobuf:"varint,3,opt,name=tombstone,proto3" json:"tombstone,omitempty"`
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SiblingData) Reset() {
	*x = SiblingData{}
	mi := &file_internal_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SiblingData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SiblingData) ProtoMessage() {}

func (x *SiblingData) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SiblingData.ProtoReflect.Descriptor instead.
func (*SiblingData) Descriptor() ([]byte, []int) {
	return file_internal_proto_rawDescGZIP(), []int{1}
}

func (x *SiblingData) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *SiblingData) GetContext() []*ContextEntry {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *SiblingData) GetTombstone() bool {
	if x != nil {
		return x.Tombstone
	}
	return false
}

func (x *SiblingData) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type ContextEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Counter       uint64                 `protobuf:"varint,2,opt,name=counter,proto3" json:"counter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContextEntry) Reset() {
	*x = ContextEntry{}
	mi := &file_internal_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContextEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContextEntry) ProtoMessage() {}

func (x *ContextEntry) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContextEntry.ProtoReflect.Descriptor instead.
func (*ContextEntry) Descriptor() ([]byte, []int) {
	return file_internal_proto_rawDescGZIP(), []int{2}
}

func (x *ContextEntry) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *ContextEntry) GetCounter() uint64 {
	if x != nil {
		return x.Counter
	}
	return 0
}

type ReplicateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplicateResponse) Reset() {
	*x = ReplicateResponse{}
	mi := &file_internal_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplicateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicateResponse) ProtoMessage() {}

func (x *ReplicateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicateResponse.ProtoReflect.Descriptor instead.
func (*ReplicateResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_rawDescGZIP(), []int{3}
}

func (x *ReplicateResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ReplicateResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type InternalReadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           []byte                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	CoordinatorId string                 `protobuf:"bytes,2,opt,name=coordinator_id,json=coordinatorId,proto3" json:"coordinator_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InternalReadRequest) Reset() {
	*x = InternalReadRequest{}
	mi := &file_internal_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InternalReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InternalReadRequest) ProtoMessage() {}

func (x *InternalReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InternalReadRequest.ProtoReflect.Descriptor instead.
func (*InternalReadRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_rawDescGZIP(), []int{4}
}

func (x *InternalReadRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *InternalReadRequest) GetCoordinatorId() string {
	if x != nil {
		return x.CoordinatorId
	}
	return ""
}

type InternalReadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Siblings      []*SiblingData         `protobuf:"bytes,1,rep,name=siblings,proto3" json:"siblings,omitempty"`
	Found         bool                   `protobuf:"varint,2,opt,name=found,proto3" json:"found,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InternalReadResponse) Reset() {
	*x = InternalReadResponse{}
	mi := &file_internal_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InternalReadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InternalReadResponse) ProtoMessage() {}

func (x *InternalReadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InternalReadResponse.ProtoReflect.Descriptor instead.
func (*InternalReadResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_rawDescGZIP(), []int{5}
}

func (x *InternalReadResponse) GetSiblings() []*SiblingData {
	if x != nil {
		return x.Siblings
	}
	return nil
}

func (x *InternalReadResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SenderId      string                 `protobuf:"bytes,1,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	Status        NodeStatus             `protobuf:"varint,4,opt,name=status,proto3,enum=goquorum.internal.v1.NodeStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_internal_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_rawDescGZIP(), []int{6}
}

func (x *HeartbeatRequest) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

func (x *HeartbeatRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *HeartbeatRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *HeartbeatRequest) GetStatus() NodeStatus {
	if x != nil {
		return x.Status
	}
	return NodeStatus_NODE_UNKNOWN
}

type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResponderId   string                 `protobuf:"bytes,1,opt,name=responder_id,json=responderId,proto3" json:"responder_id,omitempty"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Status        NodeStatus             `protobuf:"varint,3,opt,name=status,proto3,enum=goquorum.internal.v1.NodeStatus" json:"status,omitempty"`
	Peers         []*PeerStatusInfo      `protobuf:"bytes,4,rep,name=peers,proto3" json:"peers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_internal_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_rawDescGZIP(), []int{7}
}

func (x *HeartbeatResponse) GetResponderId() string {
	if x != nil {
		return x.ResponderId
	}
	return ""
}

func (x *HeartbeatResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *HeartbeatResponse) GetStatus() NodeStatus {
	if x != nil {
		return x.Status
	}
	return NodeStatus_NODE_UNKNOWN
}

func (x *HeartbeatResponse) GetPeers() []*PeerStatusInfo {
	if x != nil {
		return x.Peers
	}
	return nil
}

type PeerStatusInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Status        NodeStatus             `protobuf:"varint,2,opt,name=status,proto3,enum=goquorum.internal.v1.NodeStatus" json:"status,omitempty"`
	LastSeen      int64                  `protobuf:"varint,3,opt,name=last_seen,json=lastSeen,proto3" json:"last_seen,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeerStatusInfo) Reset() {
	*x = PeerStatusInfo{}
	mi := &file_internal_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerStatusInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerStatusInfo) ProtoMessage() {}

func (x *PeerStatusInfo) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerStatusInfo.ProtoReflect.Descriptor instead.
func (*PeerStatusInfo) Descriptor() ([]byte, []int) {
	return file_internal_proto_rawDescGZIP(), []int{8}
}

func (x *PeerStatusInfo) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *PeerStatusInfo) GetStatus() NodeStatus {
	if x != nil {
		return x.Status
	}
	return NodeStatus_NODE_UNKNOWN
}

func (x *PeerStatusInfo) GetLastSeen() int64 {
	if x != nil {
		return x.LastSeen
	}
	return 0
}

type AntiEntropyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SenderId      string                 `protobuf:"bytes,1,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	RangeStart    []byte                 `protobuf:"bytes,2,opt,name=range_start,json=rangeStart,proto3" json:"range_start,omitempty"` // Key range start (inclusive)
	RangeEnd      []byte                 `protobuf:"bytes,3,opt,name=range_end,json=rangeEnd,proto3" json:"range_end,omitempty"`       // Key range end (exclusive)
	MerkleRoot    []byte                 `protobuf:"bytes,4,opt,name=merkle_root,json=merkleRoot,proto3" json:"merkle_root,omitempty"` // Merkle tree root hash
	Phase         AntiEntropyPhase       `protobuf:"varint,5,opt,name=phase,proto3,enum=goquorum.internal.v1.AntiEntropyPhase" json:"phase,omitempty"`
	TreeHashes    [][]byte               `protobuf:"bytes,6,rep,name=tree_hashes,json=treeHashes,proto3" json:"tree_hashes,omitempty"` // For tree traversal
	Level         int32                  `protobuf:"varint,7,opt,name=level,proto3" json:"level,omitempty"`                            // Current tree level
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AntiEntropyRequest) Reset() {
	*x = AntiEntropyRequest{}
	mi := &file_internal_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AntiEntropyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AntiEntropyRequest) ProtoMessage() {}

func (x *AntiEntropyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AntiEntropyRequest.ProtoReflect.Descriptor instead.
func (*AntiEntropyRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_rawDescGZIP(), []int{9}
}

func (x *AntiEntropyRequest) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

func (x *AntiEntropyRequest) GetRangeStart() []byte {
	if x != nil {
		return x.RangeStart
	}
	return nil
}

func (x *AntiEntropyRequest) GetRangeEnd() []byte {
	if x != nil {
		return x.RangeEnd
	}
	return nil
}

func (x *AntiEntropyRequest) GetMerkleRoot() []byte {
	if x != nil {
		return x.MerkleRoot
	}
	return nil
}

func (x *AntiEntropyRequest) GetPhase() AntiEntropyPhase {
	if x != nil {
		return x.Phase
	}
	return AntiEntropyPhase_COMPARE_ROOT
}

func (x *AntiEntropyRequest) GetTreeHashes() [][]byte {
	if x != nil {
		return x.TreeHashes
	}
	return nil
}

func (x *AntiEntropyRequest) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

type AntiEntropyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InSync        bool                   `protobuf:"varint,1,opt,name=in_sync,json=inSync,proto3" json:"in_sync,omitempty"`
	MerkleRoot    []byte                 `protobuf:"bytes,2,opt,name=merkle_root,json=merkleRoot,proto3" json:"merkle_root,omitempty"`
	TreeHashes    [][]byte               `protobuf:"bytes,3,rep,name=tree_hashes,json=treeHashes,proto3" json:"tree_hashes,omitempty"`
	Keys          []*KeyVersion          `protobuf:"bytes,4,rep,name=keys,proto3" json:"keys,omitempty"` // Keys in differing ranges
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AntiEntropyResponse) Reset() {
	*x = AntiEntropyResponse{}
	mi := &file_internal_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AntiEntropyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AntiEntropyResponse) ProtoMessage() {}

func (x *AntiEntropyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AntiEntropyResponse.ProtoReflect.Descriptor instead.
func (*AntiEntropyResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_rawDescGZIP(), []int{10}
}

func (x *AntiEntropyResponse) GetInSync() bool {
	if x != nil {
		return x.InSync
	}
	return false
}

func (x *AntiEntropyResponse) GetMerkleRoot() []byte {
	if x != nil {
		return x.MerkleRoot
	}
	return nil
}

func (x *AntiEntropyResponse) GetTreeHashes() [][]byte {
	if x != nil {
		return x.TreeHashes
	}
	return nil
}

func (x *AntiEntropyResponse) GetKeys() []*KeyVersion {
	if x != nil {
		return x.Keys
	}
	return nil
}

type KeyVersion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           []byte                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Context       []*ContextEntry        `protobuf:"bytes,2,rep,name=context,proto3" json:"context,omitempty"`
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Value         []byte                 `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	Tombstone     bool                   `protobuf:"varint,5,opt,name=tombstone,proto3" json:"tombstone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyVersion) Reset() {
	*x = KeyVersion{}
	mi := &file_internal_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyVersion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyVersion) ProtoMessage() {}

func (x *KeyVersion) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyVersion.ProtoReflect.Descriptor instead.
func (*KeyVersion) Descriptor() ([]byte, []int) {
	return file_internal_proto_rawDescGZIP(), []int{11}
}

func (x *KeyVersion) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *KeyVersion) GetContext() []*ContextEntry {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *KeyVersion) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *KeyVersion) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *KeyVersion) GetTombstone() bool {
	if x != nil {
		return x.Tombstone
	}
	return false
}

type GetMerkleRootRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SenderId      string                 `protobuf:"bytes,1,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMerkleRootRequest) Reset() {
	*x = GetMerkleRootRequest{}
	mi := &file_internal_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMerkleRootRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMerkleRootRequest) ProtoMessage() {}

func (x *GetMerkleRootRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMerkleRootRequest.ProtoReflect.Descriptor instead.
func (*GetMerkleRootRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_rawDescGZIP(), []int{12}
}

func (x *GetMerkleRootRequest) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

type GetMerkleRootResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MerkleRoot    []byte                 `protobuf:"bytes,1,opt,name=merkle_root,json=merkleRoot,proto3" json:"merkle_root,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMerkleRootResponse) Reset() {
	*x = GetMerkleRootResponse{}
	mi := &file_internal_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMerkleRootResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMerkleRootResponse) ProtoMessage() {}

func (x *GetMerkleRootResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMerkleRootResponse.ProtoReflect.Descriptor instead.
func (*GetMerkleRootResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_rawDescGZIP(), []int{13}
}

func (x *GetMerkleRootResponse) GetMerkleRoot() []byte {
	if x != nil {
		return x.MerkleRoot
	}
	return nil
}

var File_internal_proto protoreflect.FileDescriptor

const file_internal_proto_rawDesc = "" +
	"\n" +
	"\x0einternal.proto\x12\x14goquorum.internal.v1\"\xa7\x01\n" +
	"\x10ReplicateRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key\x12;\n" +
	"\asibling\x18\x02 \x01(\v2!.goquorum.internal.v1.SiblingDataR\asibling\x12%\n" +
	"\x0ecoordinator_id\x18\x03 \x01(\tR\rcoordinatorId\x12\x1d\n" +
	"\n" +
	"request_id\x18\x04 \x01(\x03R\trequestId\"\x9d\x01\n" +
	"\vSiblingData\x12\x14\n" +
	"\x05value\x18\x01 \x01(\fR\x05value\x12<\n" +
	"\acontext\x18\x02 \x03(\v2\".goquorum.internal.v1.ContextEntryR\acontext\x12\x1c\n" +
	"\ttombstone\x18\x03 \x01(\bR\ttombstone\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\"A\n" +
	"\fContextEntry\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x18\n" +
	"\acounter\x18\x02 \x01(\x04R\acounter\"C\n" +
	"\x11ReplicateResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"N\n" +
	"\x13InternalReadRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key\x12%\n" +
	"\x0ecoordinator_id\x18\x02 \x01(\tR\rcoordinatorId\"k\n" +
	"\x14InternalReadResponse\x12=\n" +
	"\bsiblings\x18\x01 \x03(\v2!.goquorum.internal.v1.SiblingDataR\bsiblings\x12\x14\n" +
	"\x05found\x18\x02 \x01(\bR\x05found\"\xa1\x01\n" +
	"\x10HeartbeatRequest\x12\x1b\n" +
	"\tsender_id\x18\x01 \x01(\tR\bsenderId\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x128\n" +
	"\x06status\x18\x04 \x01(\x0e2 .goquorum.internal.v1.NodeStatusR\x06status\"\xca\x01\n" +
	"\x11HeartbeatResponse\x12!\n" +
	"\fresponder_id\x18\x01 \x01(\tR\vresponderId\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x128\n" +
	"\x06status\x18\x03 \x01(\x0e2 .goquorum.internal.v1.NodeStatusR\x06status\x12:\n" +
	"\x05peers\x18\x04 \x03(\v2$.goquorum.internal.v1.PeerStatusInfoR\x05peers\"\x80\x01\n" +
	"\x0ePeerStatusInfo\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x128\n" +
	"\x06status\x18\x02 \x01(\x0e2 .goquorum.internal.v1.NodeStatusR\x06status\x12\x1b\n" +
	"\tlast_seen\x18\x03 \x01(\x03R\blastSeen\"\x85\x02\n" +
	"\x12AntiEntropyRequest\x12\x1b\n" +
	"\tsender_id\x18\x01 \x01(\tR\bsenderId\x12\x1f\n" +
	"\vrange_start\x18\x02 \x01(\fR\n" +
	"rangeStart\x12\x1b\n" +
	"\trange_end\x18\x03 \x01(\fR\brangeEnd\x12\x1f\n" +
	"\vmerkle_root\x18\x04 \x01(\fR\n" +
	"merkleRoot\x12<\n" +
	"\x05phase\x18\x05 \x01(\x0e2&.goquorum.internal.v1.AntiEntropyPhaseR\x05phase\x12\x1f\n" +
	"\vtree_hashes\x18\x06 \x03(\fR\n" +
	"treeHashes\x12\x14\n" +
	"\x05level\x18\a \x01(\x05R\x05level\"\xa6\x01\n" +
	"\x13AntiEntropyResponse\x12\x17\n" +
	"\ain_sync\x18\x01 \x01(\bR\x06inSync\x12\x1f\n" +
	"\vmerkle_root\x18\x02 \x01(\fR\n" +
	"merkleRoot\x12\x1f\n" +
	"\vtree_hashes\x18\x03 \x03(\fR\n" +
	"treeHashes\x124\n" +
	"\x04keys\x18\x04 \x03(\v2 .goquorum.internal.v1.KeyVersionR\x04keys\"\xae\x01\n" +
	"\n" +
	"KeyVersion\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key\x12<\n" +
	"\acontext\x18\x02 \x03(\v2\".goquorum.internal.v1.ContextEntryR\acontext\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\x12\x14\n" +
	"\x05value\x18\x04 \x01(\fR\x05value\x12\x1c\n" +
	"\ttombstone\x18\x05 \x01(\bR\ttombstone\"3\n" +
	"\x14GetMerkleRootRequest\x12\x1b\n" +
	"\tsender_id\x18\x01 \x01(\tR\bsenderId\"8\n" +
	"\x15GetMerkleRootResponse\x12\x1f\n" +
	"\vmerkle_root\x18\x01 \x01(\fR\n" +
	"merkleRoot*S\n" +
	"\n" +
	"NodeStatus\x12\x10\n" +
	"\fNODE_UNKNOWN\x10\x00\x12\x10\n" +
	"\fNODE_JOINING\x10\x01\x12\x0f\n" +
	"\vNODE_ACTIVE\x10\x02\x12\x10\n" +
	"\fNODE_LEAVING\x10\x03*J\n" +
	"\x10AntiEntropyPhase\x12\x10\n" +
	"\fCOMPARE_ROOT\x10\x00\x12\x11\n" +
	"\rCOMPARE_LEVEL\x10\x01\x12\x11\n" +
	"\rEXCHANGE_KEYS\x10\x022\x83\x04\n" +
	"\x10GoQuorumInternal\x12\\\n" +
	"\tReplicate\x12&.goquorum.internal.v1.ReplicateRequest\x1a'.goquorum.internal.v1.ReplicateResponse\x12]\n" +
	"\x04Read\x12).goquorum.internal.v1.InternalReadRequest\x1a*.goquorum.internal.v1.InternalReadResponse\x12\\\n" +
	"\tHeartbeat\x12&.goquorum.internal.v1.HeartbeatRequest\x1a'.goquorum.internal.v1.HeartbeatResponse\x12j\n" +
	"\x13AntiEntropyExchange\x12(.goquorum.internal.v1.AntiEntropyRequest\x1a).goquorum.internal.v1.AntiEntropyResponse\x12h\n" +
	"\rGetMerkleRoot\x12*.goquorum.internal.v1.GetMerkleRootRequest\x1a+.goquorum.internal.v1.GetMerkleRootResponseB%Z#GoQuorum/api/internal/v1;internalv1b\x06proto3"

var (
	file_internal_proto_rawDescOnce sync.Once
	file_internal_proto_rawDescData []byte
)

func file_internal_proto_rawDescGZIP() []byte {
	file_internal_proto_rawDescOnce.Do(func() {
		file_internal_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_proto_rawDesc), len(file_internal_proto_rawDesc)))
	})
	return file_internal_proto_rawDescData
}

var file_internal_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_internal_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_internal_proto_goTypes = []any{
	(NodeStatus)(0),               // 0: goquorum.internal.v1.NodeStatus
	(AntiEntropyPhase)(0),         // 1: goquorum.internal.v1.AntiEntropyPhase
	(*ReplicateRequest)(nil),      // 2: goquorum.internal.v1.ReplicateRequest
	(*SiblingData)(nil),           // 3: goquorum.internal.v1.SiblingData
	(*ContextEntry)(nil),          // 4: goquorum.internal.v1.ContextEntry
	(*ReplicateResponse)(nil),     // 5: goquorum.internal.v1.ReplicateResponse
	(*InternalReadRequest)(nil),   // 6: goquorum.internal.v1.InternalReadRequest
	(*InternalReadResponse)(nil),  // 7: goquorum.internal.v1.InternalReadResponse
	(*HeartbeatRequest)(nil),      // 8: goquorum.internal.v1.HeartbeatRequest
	(*HeartbeatResponse)(nil),     // 9: goquorum.internal.v1.HeartbeatResponse
	(*PeerStatusInfo)(nil),        // 10: goquorum.internal.v1.PeerStatusInfo
	(*AntiEntropyRequest)(nil),    // 11: goquorum.internal.v1.AntiEntropyRequest
	(*AntiEntropyResponse)(nil),   // 12: goquorum.internal.v1.AntiEntropyResponse
	(*KeyVersion)(nil),            // 13: goquorum.internal.v1.KeyVersion
	(*GetMerkleRootRequest)(nil),  // 14: goquorum.internal.v1.GetMerkleRootRequest
	(*GetMerkleRootResponse)(nil), // 15: goquorum.internal.v1.GetMerkleRootResponse
}
var file_internal_proto_depIdxs = []int32{
	3,  // 0: goquorum.internal.v1.ReplicateRequest.sibling:type_name -> goquorum.internal.v1.SiblingData
	4,  // 1: goquorum.internal.v1.SiblingData.context:type_name -> goquorum.internal.v1.ContextEntry
	3,  // 2: goquorum.internal.v1.InternalReadResponse.siblings:type_name -> goquorum.internal.v1.SiblingData
	0,  // 3: goquorum.internal.v1.HeartbeatRequest.status:type_name -> goquorum.internal.v1.NodeStatus
	0,  // 4: goquorum.internal.v1.HeartbeatResponse.status:type_name -> goquorum.internal.v1.NodeStatus
	10, // 5: goquorum.internal.v1.HeartbeatResponse.peers:type_name -> goquorum.internal.v1.PeerStatusInfo
	0,  // 6: goquorum.internal.v1.PeerStatusInfo.status:type_name -> goquorum.internal.v1.NodeStatus
	1,  // 7: goquorum.internal.v1.AntiEntropyRequest.phase:type_name -> goquorum.internal.v1.AntiEntropyPhase
	13, // 8: goquorum.internal.v1.AntiEntropyResponse.keys:type_name -> goquorum.internal.v1.KeyVersion
	4,  // 9: goquorum.internal.v1.KeyVersion.context:type_name -> goquorum.internal.v1.ContextEntry
	2,  // 10: goquorum.internal.v1.GoQuorumInternal.Replicate:input_type -> goquorum.internal.v1.ReplicateRequest
	6,  // 11: goquorum.internal.v1.GoQuorumInternal.Read:input_type -> goquorum.internal.v1.InternalReadRequest
	8,  // 12: goquorum.internal.v1.GoQuorumInternal.Heartbeat:input_type -> goquorum.internal.v1.HeartbeatRequest
	11, // 13: goquorum.internal.v1.GoQuorumInternal.AntiEntropyExchange:input_type -> goquorum.internal.v1.AntiEntropyRequest
	14, // 14: goquorum.internal.v1.GoQuorumInternal.GetMerkleRoot:input_type -> goquorum.internal.v1.GetMerkleRootRequest
	5,  // 15: goquorum.internal.v1.GoQuorumInternal.Replicate:output_type -> goquorum.internal.v1.ReplicateResponse
	7,  // 16: goquorum.internal.v1.GoQuorumInternal.Read:output_type -> goquorum.internal.v1.InternalReadResponse
	9,  // 17: goquorum.internal.v1.GoQuorumInternal.Heartbeat:output_type -> goquorum.internal.v1.HeartbeatResponse
	12, // 18: goquorum.internal.v1.GoQuorumInternal.AntiEntropyExchange:output_type -> goquorum.internal.v1.AntiEntropyResponse
	15, // 19: goquorum.internal.v1.GoQuorumInternal.GetMerkleRoot:output_type -> goquorum.internal.v1.GetMerkleRootResponse
	15, // [15:20] is the sub-list for method output_type
	10, // [10:15] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_internal_proto_init() }
func file_internal_proto_init() {
	if File_internal_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_proto_rawDesc), len(file_internal_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_proto_goTypes,
		DependencyIndexes: file_internal_proto_depIdxs,
		EnumInfos:         file_internal_proto_enumTypes,
		MessageInfos:      file_internal_proto_msgTypes,
	}.Build()
	File_internal_proto = out.File
	file_internal_proto_goTypes = nil
	file_internal_proto_depIdxs = nil
}
