// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: goquorum.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GoQuorum_Get_FullMethodName      = "/goquorum.v1.GoQuorum/Get"
	GoQuorum_Put_FullMethodName      = "/goquorum.v1.GoQuorum/Put"
	GoQuorum_Delete_FullMethodName   = "/goquorum.v1.GoQuorum/Delete"
	GoQuorum_BatchGet_FullMethodName = "/goquorum.v1.GoQuorum/BatchGet"
	GoQuorum_BatchPut_FullMethodName = "/goquorum.v1.GoQuorum/BatchPut"
)

// GoQuorumClient is the client API for GoQuorum service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GoQuorumClient interface {
	// Get retrieves value(s) for a key
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error)
	// Put stores a value for a key
	Put(ctx context.Context, in *PutRequest, opts ...grpc.CallOption) (*PutResponse, error)
	// Delete removes a key by writing a tombstone
	Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error)
	// BatchGet retrieves values for multiple keys
	BatchGet(ctx context.Context, in *BatchGetRequest, opts ...grpc.CallOption) (*BatchGetResponse, error)
	// BatchPut stores multiple key-value pairs
	BatchPut(ctx context.Context, in *BatchPutRequest, opts ...grpc.CallOption) (*BatchPutResponse, error)
}

type goQuorumClient struct {
	cc grpc.ClientConnInterface
}

func NewGoQuorumClient(cc grpc.ClientConnInterface) GoQuorumClient {
	return &goQuorumClient{cc}
}

func (c *goQuorumClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetResponse)
	err := c.cc.Invoke(ctx, GoQuorum_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goQuorumClient) Put(ctx context.Context, in *PutRequest, opts ...grpc.CallOption) (*PutResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PutResponse)
	err := c.cc.Invoke(ctx, GoQuorum_Put_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goQuorumClient) Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteResponse)
	err := c.cc.Invoke(ctx, GoQuorum_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goQuorumClient) BatchGet(ctx context.Context, in *BatchGetRequest, opts ...grpc.CallOption) (*BatchGetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchGetResponse)
	err := c.cc.Invoke(ctx, GoQuorum_BatchGet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goQuorumClient) BatchPut(ctx context.Context, in *BatchPutRequest, opts ...grpc.CallOption) (*BatchPutResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchPutResponse)
	err := c.cc.Invoke(ctx, GoQuorum_BatchPut_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GoQuorumServer is the server API for GoQuorum service.
// All implementations must embed UnimplementedGoQuorumServer
// for forward compatibility.
type GoQuorumServer interface {
	// Get retrieves value(s) for a key
	Get(context.Context, *GetRequest) (*GetResponse, error)
	// Put stores a value for a key
	Put(context.Context, *PutRequest) (*PutResponse, error)
	// Delete removes a key by writing a tombstone
	Delete(context.Context, *DeleteRequest) (*DeleteResponse, error)
	// BatchGet retrieves values for multiple keys
	BatchGet(context.Context, *BatchGetRequest) (*BatchGetResponse, error)
	// BatchPut stores multiple key-value pairs
	BatchPut(context.Context, *BatchPutRequest) (*BatchPutResponse, error)
	mustEmbedUnimplementedGoQuorumServer()
}

// UnimplementedGoQuorumServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGoQuorumServer struct{}

func (UnimplementedGoQuorumServer) Get(context.Context, *GetRequest) (*GetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedGoQuorumServer) Put(context.Context, *PutRequest) (*PutResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Put not implemented")
}
func (UnimplementedGoQuorumServer) Delete(context.Context, *DeleteRequest) (*DeleteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedGoQuorumServer) BatchGet(context.Context, *BatchGetRequest) (*BatchGetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BatchGet not implemented")
}
func (UnimplementedGoQuorumServer) BatchPut(context.Context, *BatchPutRequest) (*BatchPutResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BatchPut not implemented")
}
func (UnimplementedGoQuorumServer) mustEmbedUnimplementedGoQuorumServer() {}
func (UnimplementedGoQuorumServer) testEmbeddedByValue()                  {}

// UnsafeGoQuorumServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GoQuorumServer will
// result in compilation errors.
type UnsafeGoQuorumServer interface {
	mustEmbedUnimplementedGoQuorumServer()
}

func RegisterGoQuorumServer(s grpc.ServiceRegistrar, srv GoQuorumServer) {
	// If the following call panics, it indicates UnimplementedGoQuorumServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GoQuorum_ServiceDesc, srv)
}

func _GoQuorum_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoQuorumServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GoQuorum_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoQuorumServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoQuorum_Put_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoQuorumServer).Put(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GoQuorum_Put_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoQuorumServer).Put(ctx, req.(*PutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoQuorum_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoQuorumServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GoQuorum_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoQuorumServer).Delete(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoQuorum_BatchGet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoQuorumServer).BatchGet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GoQuorum_BatchGet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoQuorumServer).BatchGet(ctx, req.(*BatchGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoQuorum_BatchPut_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchPutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoQuorumServer).BatchPut(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GoQuorum_BatchPut_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoQuorumServer).BatchPut(ctx, req.(*BatchPutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GoQuorum_ServiceDesc is the grpc.ServiceDesc for GoQuorum service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GoQuorum_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "goquorum.v1.GoQuorum",
	HandlerType: (*GoQuorumServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _GoQuorum_Get_Handler,
		},
		{
			MethodName: "Put",
			Handler:    _GoQuorum_Put_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _GoQuorum_Delete_Handler,
		},
		{
			MethodName: "BatchGet",
			Handler:    _GoQuorum_BatchGet_Handler,
		},
		{
			MethodName: "BatchPut",
			Handler:    _GoQuorum_BatchPut_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "goquorum.proto",
}

const (
	GoQuorumAdmin_Health_FullMethodName            = "/goquorum.v1.GoQuorumAdmin/Health"
	GoQuorumAdmin_ClusterInfo_FullMethodName       = "/goquorum.v1.GoQuorumAdmin/ClusterInfo"
	GoQuorumAdmin_GetMetrics_FullMethodName        = "/goquorum.v1.GoQuorumAdmin/GetMetrics"
	GoQuorumAdmin_KeyInfo_FullMethodName           = "/goquorum.v1.GoQuorumAdmin/KeyInfo"
	GoQuorumAdmin_TriggerCompaction_FullMethodName = "/goquorum.v1.GoQuorumAdmin/TriggerCompaction"
)

// GoQuorumAdminClient is the client API for GoQuorumAdmin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GoQuorumAdminClient interface {
	// Health returns node health status
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
	// ClusterInfo returns cluster membership and status
	ClusterInfo(ctx context.Context, in *ClusterInfoRequest, opts ...grpc.CallOption) (*ClusterInfoResponse, error)
	// GetMetrics returns Prometheus-format metrics
	GetMetrics(ctx context.Context, in *GetMetricsRequest, opts ...grpc.CallOption) (*GetMetricsResponse, error)
	// KeyInfo returns detailed information about a specific key
	KeyInfo(ctx context.Context, in *KeyInfoRequest, opts ...grpc.CallOption) (*KeyInfoResponse, error)
	// TriggerCompaction manually triggers Pebble compaction
	TriggerCompaction(ctx context.Context, in *TriggerCompactionRequest, opts ...grpc.CallOption) (*TriggerCompactionResponse, error)
}

type goQuorumAdminClient struct {
	cc grpc.ClientConnInterface
}

func NewGoQuorumAdminClient(cc grpc.ClientConnInterface) GoQuorumAdminClient {
	return &goQuorumAdminClient{cc}
}

func (c *goQuorumAdminClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, GoQuorumAdmin_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goQuorumAdminClient) ClusterInfo(ctx context.Context, in *ClusterInfoRequest, opts ...grpc.CallOption) (*ClusterInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClusterInfoResponse)
	err := c.cc.Invoke(ctx, GoQuorumAdmin_ClusterInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goQuorumAdminClient) GetMetrics(ctx context.Context, in *GetMetricsRequest, opts ...grpc.CallOption) (*GetMetricsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMetricsResponse)
	err := c.cc.Invoke(ctx, GoQuorumAdmin_GetMetrics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goQuorumAdminClient) KeyInfo(ctx context.Context, in *KeyInfoRequest, opts ...grpc.CallOption) (*KeyInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KeyInfoResponse)
	err := c.cc.Invoke(ctx, GoQuorumAdmin_KeyInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goQuorumAdminClient) TriggerCompaction(ctx context.Context, in *TriggerCompactionRequest, opts ...grpc.CallOption) (*TriggerCompactionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TriggerCompactionResponse)
	err := c.cc.Invoke(ctx, GoQuorumAdmin_TriggerCompaction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GoQuorumAdminServer is the server API for GoQuorumAdmin service.
// All implementations must embed UnimplementedGoQuorumAdminServer
// for forward compatibility.
type GoQuorumAdminServer interface {
	// Health returns node health status
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	// ClusterInfo returns cluster membership and status
	ClusterInfo(context.Context, *ClusterInfoRequest) (*ClusterInfoResponse, error)
	// GetMetrics returns Prometheus-format metrics
	GetMetrics(context.Context, *GetMetricsRequest) (*GetMetricsResponse, error)
	// KeyInfo returns detailed information about a specific key
	KeyInfo(context.Context, *KeyInfoRequest) (*KeyInfoResponse, error)
	// TriggerCompaction manually triggers Pebble compaction
	TriggerCompaction(context.Context, *TriggerCompactionRequest) (*TriggerCompactionResponse, error)
	mustEmbedUnimplementedGoQuorumAdminServer()
}

// UnimplementedGoQuorumAdminServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGoQuorumAdminServer struct{}

func (UnimplementedGoQuorumAdminServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedGoQuorumAdminServer) ClusterInfo(context.Context, *ClusterInfoRequest) (*ClusterInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ClusterInfo not implemented")
}
func (UnimplementedGoQuorumAdminServer) GetMetrics(context.Context, *GetMetricsRequest) (*GetMetricsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMetrics not implemented")
}
func (UnimplementedGoQuorumAdminServer) KeyInfo(context.Context, *KeyInfoRequest) (*KeyInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method KeyInfo not implemented")
}
func (UnimplementedGoQuorumAdminServer) TriggerCompaction(context.Context, *TriggerCompactionRequest) (*TriggerCompactionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TriggerCompaction not implemented")
}
func (UnimplementedGoQuorumAdminServer) mustEmbedUnimplementedGoQuorumAdminServer() {}
func (UnimplementedGoQuorumAdminServer) testEmbeddedByValue()                       {}

// UnsafeGoQuorumAdminServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GoQuorumAdminServer will
// result in compilation errors.
type UnsafeGoQuorumAdminServer interface {
	mustEmbedUnimplementedGoQuorumAdminServer()
}

func RegisterGoQuorumAdminServer(s grpc.ServiceRegistrar, srv GoQuorumAdminServer) {
	// If the following call panics, it indicates UnimplementedGoQuorumAdminServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GoQuorumAdmin_ServiceDesc, srv)
}

func _GoQuorumAdmin_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoQuorumAdminServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GoQuorumAdmin_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoQuorumAdminServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoQuorumAdmin_ClusterInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClusterInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoQuorumAdminServer).ClusterInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GoQuorumAdmin_ClusterInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoQuorumAdminServer).ClusterInfo(ctx, req.(*ClusterInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoQuorumAdmin_GetMetrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMetricsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoQuorumAdminServer).GetMetrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GoQuorumAdmin_GetMetrics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoQuorumAdminServer).GetMetrics(ctx, req.(*GetMetricsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoQuorumAdmin_KeyInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KeyInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoQuorumAdminServer).KeyInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GoQuorumAdmin_KeyInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoQuorumAdminServer).KeyInfo(ctx, req.(*KeyInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoQuorumAdmin_TriggerCompaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TriggerCompactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoQuorumAdminServer).TriggerCompaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GoQuorumAdmin_TriggerCompaction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoQuorumAdminServer).TriggerCompaction(ctx, req.(*TriggerCompactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GoQuorumAdmin_ServiceDesc is the grpc.ServiceDesc for GoQuorumAdmin service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GoQuorumAdmin_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "goquorum.v1.GoQuorumAdmin",
	HandlerType: (*GoQuorumAdminServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Health",
			Handler:    _GoQuorumAdmin_Health_Handler,
		},
		{
			MethodName: "ClusterInfo",
			Handler:    _GoQuorumAdmin_ClusterInfo_Handler,
		},
		{
			MethodName: "GetMetrics",
			Handler:    _GoQuorumAdmin_GetMetrics_Handler,
		},
		{
			MethodName: "KeyInfo",
			Handler:    _GoQuorumAdmin_KeyInfo_Handler,
		},
		{
			MethodName: "TriggerCompaction",
			Handler:    _GoQuorumAdmin_TriggerCompaction_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "goquorum.proto",
}
