// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: goquorum.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HealthStatus int32

const (
	HealthStatus_HEALTH_UNKNOWN   HealthStatus = 0
	HealthStatus_HEALTH_HEALTHY   HealthStatus = 1
	HealthStatus_HEALTH_DEGRADED  HealthStatus = 2
	HealthStatus_HEALTH_UNHEALTHY HealthStatus = 3
)

// Enum value maps for HealthStatus.
var (
	HealthStatus_name = map[int32]string{
		0: "HEALTH_UNKNOWN",
		1: "HEALTH_HEALTHY",
		2: "HEALTH_DEGRADED",
		3: "HEALTH_UNHEALTHY",
	}
	HealthStatus_value = map[string]int32{
		"HEALTH_UNKNOWN":   0,
		"HEALTH_HEALTHY":   1,
		"HEALTH_DEGRADED":  2,
		"HEALTH_UNHEALTHY": 3,
	}
)

func (x HealthStatus) Enum() *HealthStatus {
	p := new(HealthStatus)
	*p = x
	return p
}

func (x HealthStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HealthStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_goquorum_proto_enumTypes[0].Descriptor()
}

func (HealthStatus) Type() protoreflect.EnumType {
	return &file_goquorum_proto_enumTypes[0]
}

func (x HealthStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HealthStatus.Descriptor instead.
func (HealthStatus) EnumDescriptor() ([]byte, []int) {
	return file_goquorum_proto_rawDescGZIP(), []int{0}
}

type PeerStatus int32

const (
	PeerStatus_PEER_UNKNOWN PeerStatus = 0
	PeerStatus_PEER_ACTIVE  PeerStatus = 1
	PeerStatus_PEER_SUSPECT PeerStatus = 2
	PeerStatus_PEER_FAILED  PeerStatus = 3
)

// Enum value maps for PeerStatus.
var (
	PeerStatus_name = map[int32]string{
		0: "PEER_UNKNOWN",
		1: "PEER_ACTIVE",
		2: "PEER_SUSPECT",
		3: "PEER_FAILED",
	}
	PeerStatus_value = map[string]int32{
		"PEER_UNKNOWN": 0,
		"PEER_ACTIVE":  1,
		"PEER_SUSPECT": 2,
		"PEER_FAILED":  3,
	}
)

func (x PeerStatus) Enum() *PeerStatus {
	p := new(PeerStatus)
	*p = x
	return p
}

func (x PeerStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PeerStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_goquorum_proto_enumTypes[1].Descriptor()
}

func (PeerStatus) Type() protoreflect.EnumType {
	return &file_goquorum_proto_enumTypes[1]
}

func (x PeerStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PeerStatus.Descriptor instead.
func (PeerStatus) EnumDescriptor() ([]byte, []int) {
	return file_goquorum_proto_rawDescGZIP(), []int{1}
}

type ClusterStatus int32

const (
	ClusterStatus_CLUSTER_UNKNOWN  ClusterStatus = 0
	ClusterStatus_CLUSTER_HEALTHY  ClusterStatus = 1
	ClusterStatus_CLUSTER_DEGRADED ClusterStatus = 2
	ClusterStatus_CLUSTER_CRITICAL ClusterStatus = 3
)

// Enum value maps for ClusterStatus.
var (
	ClusterStatus_name = map[int32]string{
		0: "CLUSTER_UNKNOWN",
		1: "CLUSTER_HEALTHY",
		2: "CLUSTER_DEGRADED",
		3: "CLUSTER_CRITICAL",
	}
	ClusterStatus_value = map[string]int32{
		"CLUSTER_UNKNOWN":  0,
		"CLUSTER_HEALTHY":  1,
		"CLUSTER_DEGRADED": 2,
		"CLUSTER_CRITICAL": 3,
	}
)

func (x ClusterStatus) Enum() *ClusterStatus {
	p := new(ClusterStatus)
	*p = x
	return p
}

func (x ClusterStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ClusterStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_goquorum_proto_enumTypes[2].Descriptor()
}

func (ClusterStatus) Type() protoreflect.EnumType {
	return &file_goquorum_proto_enumTypes[2]
}

func (x ClusterStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ClusterStatus.Descriptor instead.
func (ClusterStatus) EnumDescriptor() ([]byte, []int) {
	return file_goquorum_proto_rawDescGZIP(), []int{2}
}

type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           []byte                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`         // Required: key to retrieve (1-64KB)
	Options       *GetOptions            `protobuf:"bytes,2,opt,name=options,proto3" json:"options,omitempty"` // Optional: read options
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_goquorum_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_goquorum_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_goquorum_proto_rawDescGZIP(), []int{0}
}

func (x *GetRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *GetRequest) GetOptions() *GetOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

type GetOptions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	R             uint32                 `protobuf:"varint,1,opt,name=r,proto3" json:"r,omitempty"`                                  // Read quorum override (0 = use default)
	TimeoutMs     uint32                 `protobuf:"varint,2,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"` // Request timeout override (0 = use default)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOptions) Reset() {
	*x = GetOptions{}
	mi := &file_goquorum_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOptions) ProtoMessage() {}

func (x *GetOptions) ProtoReflect() protoreflect.Message {
	mi := &file_goquorum_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOptions.ProtoReflect.Descriptor instead.
func (*GetOptions) Descriptor() ([]byte, []int) {
	return file_goquorum_proto_rawDescGZIP(), []int{1}
}

func (x *GetOptions) GetR() uint32 {
	if x != nil {
		return x.R
	}
	return 0
}

func (x *GetOptions) GetTimeoutMs() uint32 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

type GetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Siblings      []*Sibling             `protobuf:"bytes,1,rep,name=siblings,proto3" json:"siblings,omitempty"` // One or more values (multiple = conflict)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_goquorum_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_goquorum_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_goquorum_proto_rawDescGZIP(), []int{2}
}

func (x *GetResponse) GetSiblings() []*Sibling {
	if x != nil {
		return x.Siblings
	}
	return nil
}

type Sibling struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         []byte                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`          // Value bytes (empty if tombstone)
	Context       *Context               `protobuf:"bytes,2,opt,name=context,proto3" json:"context,omitempty"`      // Causal context (vector clock)
	Tombstone     bool                   `protobuf:"varint,3,opt,name=tombstone,proto3" json:"tombstone,omitempty"` // True if this is a tombstone
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // Write timestamp (Unix nanos)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Sibling) Reset() {
	*x = Sibling{}
	mi := &file_goquorum_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Sibling) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sibling) ProtoMessage() {}

func (x *Sibling) ProtoReflect() protoreflect.Message {
	mi := &file_goquorum_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sibling.ProtoReflect.Descriptor instead.
func (*Sibling) Descriptor() ([]byte, []int) {
	return file_goquorum_proto_rawDescGZIP(), []int{3}
}

func (x *Sibling) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Sibling) GetContext() *Context {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *Sibling) GetTombstone() bool {
	if x != nil {
		return x.Tombstone
	}
	return false
}

func (x *Sibling) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type Context struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*ContextEntry        `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Context) Reset() {
	*x = Context{}
	mi := &file_goquorum_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Context) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Context) ProtoMessage() {}

func (x *Context) ProtoReflect() protoreflect.Message {
	mi := &file_goquorum_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Context.ProtoReflect.Descriptor instead.
func (*Context) Descriptor() ([]byte, []int) {
	return file_goquorum_proto_rawDescGZIP(), []int{4}
}

func (x *Context) GetEntries() []*ContextEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type ContextEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Counter       uint64                 `protobuf:"varint,2,opt,name=counter,proto3" json:"counter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContextEntry) Reset() {
	*x = ContextEntry{}
	mi := &file_goquorum_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContextEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContextEntry) ProtoMessage() {}

func (x *ContextEntry) ProtoReflect() protoreflect.Message {
	mi := &file_goquorum_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContextEntry.ProtoReflect.Descriptor instead.
func (*ContextEntry) Descriptor() ([]byte, []int) {
	return file_goquorum_proto_rawDescGZIP(), []int{5}
}

func (x *ContextEntry) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *ContextEntry) GetCounter() uint64 {
	if x != nil {
		return x.Counter
	}
	return 0
}

type PutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           []byte                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`         // Required: key (1-64KB)
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`     // Required: value (0-1MB)
	Context       *Context               `protobuf:"bytes,3,opt,name=context,proto3" json:"context,omitempty"` // Optional: context from previous read
	Options       *PutOptions            `protobuf:"bytes,4,opt,name=options,proto3" json:"options,omitempty"` // Optional: write options
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutRequest) Reset() {
	*x = PutRequest{}
	mi := &file_goquorum_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutRequest) ProtoMessage() {}

func (x *PutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_goquorum_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutRequest.ProtoReflect.Descriptor instead.
func (*PutRequest) Descriptor() ([]byte, []int) {
	return file_goquorum_proto_rawDescGZIP(), []int{6}
}

func (x *PutRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *PutRequest) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *PutRequest) GetContext() *Context {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *PutRequest) GetOptions() *PutOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

type PutOptions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	W             uint32                 `protobuf:"varint,1,opt,name=w,proto3" json:"w,omitempty"`                                     // Write quorum override (0 = use default)
	TimeoutMs     uint32                 `protobuf:"varint,2,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`    // Request timeout override
	TtlSeconds    int64                  `protobuf:"varint,3,opt,name=ttl_seconds,json=ttlSeconds,proto3" json:"ttl_seconds,omitempty"` // Key TTL in seconds (0 = no expiry)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutOptions) Reset() {
	*x = PutOptions{}
	mi := &file_goquorum_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutOptions) ProtoMessage() {}

func (x *PutOptions) ProtoReflect() protoreflect.Message {
	mi := &file_goquorum_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutOptions.ProtoReflect.Descriptor instead.
func (*PutOptions) Descriptor() ([]byte, []int) {
	return file_goquorum_proto_rawDescGZIP(), []int{7}
}

func (x *PutOptions) GetW() uint32 {
	if x != nil {
		return x.W
	}
	return 0
}

func (x *PutOptions) GetTimeoutMs() uint32 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

func (x *PutOptions) GetTtlSeconds() int64 {
	if x != nil {
		return x.TtlSeconds
	}
	return 0
}

type PutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Context       *Context               `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"` // New context after write
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutResponse) Reset() {
	*x = PutResponse{}
	mi := &file_goquorum_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutResponse) ProtoMessage() {}

func (x *PutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_goquorum_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutResponse.ProtoReflect.Descriptor instead.
func (*PutResponse) Descriptor() ([]byte, []int) {
	return file_goquorum_proto_rawDescGZIP(), []int{8}
}

func (x *PutResponse) GetContext() *Context {
	if x != nil {
		return x.Context
	}
	return nil
}

type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           []byte                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`         // Required: key to delete
	Context       *Context               `protobuf:"bytes,2,opt,name=context,proto3" json:"context,omitempty"` // Required: context from previous read
	Options       *DeleteOptions         `protobuf:"bytes,3,opt,name=options,proto3" json:"options,omitempty"` // Optional: delete options
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_goquorum_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_goquorum_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_goquorum_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *DeleteRequest) GetContext() *Context {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *DeleteRequest) GetOptions() *DeleteOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

type DeleteOptions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	W             uint32                 `protobuf:"varint,1,opt,name=w,proto3" json:"w,omitempty"`                                  // Write quorum override
	TimeoutMs     uint32                 `protobuf:"varint,2,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"` // Request timeout override
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteOptions) Reset() {
	*x = DeleteOptions{}
	mi := &file_goquorum_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteOptions) ProtoMessage() {}

func (x *DeleteOptions) ProtoReflect() protoreflect.Message {
	mi := &file_goquorum_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteOptions.ProtoReflect.Descriptor instead.
func (*DeleteOptions) Descriptor() ([]byte, []int) {
	return file_goquorum_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteOptions) GetW() uint32 {
	if x != nil {
		return x.W
	}
	return 0
}

func (x *DeleteOptions) GetTimeoutMs() uint32 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_goquorum_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_goquorum_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_goquorum_proto_rawDescGZIP(), []int{11}
}

type BatchGetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keys          [][]byte               `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
	Options       *GetOptions            `protobuf:"bytes,2,opt,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchGetRequest) Reset() {
	*x = BatchGetRequest{}
	mi := &file_goquorum_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGetRequest) ProtoMessage() {}

func (x *BatchGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_goquorum_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchGetRequest.ProtoReflect.Descriptor instead.
func (*BatchGetRequest) Descriptor() ([]byte, []int) {
	return file_goquorum_proto_rawDescGZIP(), []int{12}
}

func (x *BatchGetRequest) GetKeys() [][]byte {
	if x != nil {
		return x.Keys
	}
	return nil
}

func (x *BatchGetRequest) GetOptions() *GetOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

type BatchGetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*BatchGetResult      `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchGetResponse) Reset() {
	*x = BatchGetResponse{}
	mi := &file_goquorum_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchGetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGetResponse) ProtoMessage() {}

func (x *BatchGetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_goquorum_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchGetResponse.ProtoReflect.Descriptor instead.
func (*BatchGetResponse) Descriptor() ([]byte, []int) {
	return file_goquorum_proto_rawDescGZIP(), []int{13}
}

func (x *BatchGetResponse) GetResults() []*BatchGetResult {
	if x != nil {
		return x.Results
	}
	return nil
}

type BatchGetResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           []byte                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Siblings      []*Sibling             `protobuf:"bytes,2,rep,name=siblings,proto3" json:"siblings,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"` // empty if success
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchGetResult) Reset() {
	*x = BatchGetResult{}
	mi := &file_goquorum_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchGetResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGetResult) ProtoMessage() {}

func (x *BatchGetResult) ProtoReflect() protoreflect.Message {
	mi := &file_goquorum_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchGetResult.ProtoReflect.Descriptor instead.
func (*BatchGetResult) Descriptor() ([]byte, []int) {
	return file_goquorum_proto_rawDescGZIP(), []int{14}
}

func (x *BatchGetResult) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *BatchGetResult) GetSiblings() []*Sibling {
	if x != nil {
		return x.Siblings
	}
	return nil
}

func (x *BatchGetResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type BatchPutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*BatchPutItem        `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Options       *PutOptions            `protobuf:"bytes,2,opt,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchPutRequest) Reset() {
	*x = BatchPutRequest{}
	mi := &file_goquorum_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchPutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchPutRequest) ProtoMessage() {}

func (x *BatchPutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_goquorum_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchPutRequest.ProtoReflect.Descriptor instead.
func (*BatchPutRequest) Descriptor() ([]byte, []int) {
	return file_goquorum_proto_rawDescGZIP(), []int{15}
}

func (x *BatchPutRequest) GetItems() []*BatchPutItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *BatchPutRequest) GetOptions() *PutOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

type BatchPutItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           []byte                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Context       *Context               `protobuf:"bytes,3,opt,name=context,proto3" json:"context,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchPutItem) Reset() {
	*x = BatchPutItem{}
	mi := &file_goquorum_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchPutItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchPutItem) ProtoMessage() {}

func (x *BatchPutItem) ProtoReflect() protoreflect.Message {
	mi := &file_goquorum_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchPutItem.ProtoReflect.Descriptor instead.
func (*BatchPutItem) Descriptor() ([]byte, []int) {
	return file_goquorum_proto_rawDescGZIP(), []int{16}
}

func (x *BatchPutItem) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *BatchPutItem) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *BatchPutItem) GetContext() *Context {
	if x != nil {
		return x.Context
	}
	return nil
}

type BatchPutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*BatchPutResult      `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchPutResponse) Reset() {
	*x = BatchPutResponse{}
	mi := &file_goquorum_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchPutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchPutResponse) ProtoMessage() {}

func (x *BatchPutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_goquorum_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchPutResponse.ProtoReflect.Descriptor instead.
func (*BatchPutResponse) Descriptor() ([]byte, []int) {
	return file_goquorum_proto_rawDescGZIP(), []int{17}
}

func (x *BatchPutResponse) GetResults() []*BatchPutResult {
	if x != nil {
		return x.Results
	}
	return nil
}

type BatchPutResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           []byte                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Context       *Context               `protobuf:"bytes,2,opt,name=context,proto3" json:"context,omitempty"` // new context after write
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`     // empty if success
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchPutResult) Reset() {
	*x = BatchPutResult{}
	mi := &file_goquorum_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchPutResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchPutResult) ProtoMessage() {}

func (x *BatchPutResult) ProtoReflect() protoreflect.Message {
	mi := &file_goquorum_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchPutResult.ProtoReflect.Descriptor instead.
func (*BatchPutResult) Descriptor() ([]byte, []int) {
	return file_goquorum_proto_rawDescGZIP(), []int{18}
}

func (x *BatchPutResult) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *BatchPutResult) GetContext() *Context {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *BatchPutResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_goquorum_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_goquorum_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_goquorum_proto_rawDescGZIP(), []int{19}
}

type HealthResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Status        HealthStatus            `protobuf:"varint,1,opt,name=status,proto3,enum=goquorum.v1.HealthStatus" json:"status,omitempty"`
	NodeId        string                  `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	UptimeSeconds int64                   `protobuf:"varint,3,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	Version       string                  `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	Checks        map[string]*CheckResult `protobuf:"bytes,5,rep,name=checks,proto3" json:"checks,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_goquorum_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_goquorum_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_goquorum_proto_rawDescGZIP(), []int{20}
}

func (x *HealthResponse) GetStatus() HealthStatus {
	if x != nil {
		return x.Status
	}
	return HealthStatus_HEALTH_UNKNOWN
}

func (x *HealthResponse) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *HealthResponse) GetUptimeSeconds() int64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

func (x *HealthResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *HealthResponse) GetChecks() map[string]*CheckResult {
	if x != nil {
		return x.Checks
	}
	return nil
}

type CheckResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	LatencyMs     int64                  `protobuf:"varint,2,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	PeersActive   int32                  `protobuf:"varint,4,opt,name=peers_active,json=peersActive,proto3" json:"peers_active,omitempty"`
	PeersTotal    int32                  `protobuf:"varint,5,opt,name=peers_total,json=peersTotal,proto3" json:"peers_total,omitempty"`
	FreeBytes     int64                  `protobuf:"varint,6,opt,name=free_bytes,json=freeBytes,proto3" json:"free_bytes,omitempty"`
	TotalBytes    int64                  `protobuf:"varint,7,opt,name=total_bytes,json=totalBytes,proto3" json:"total_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckResult) Reset() {
	*x = CheckResult{}
	mi := &file_goquorum_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckResult) ProtoMessage() {}

func (x *CheckResult) ProtoReflect() protoreflect.Message {
	mi := &file_goquorum_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckResult.ProtoReflect.Descriptor instead.
func (*CheckResult) Descriptor() ([]byte, []int) {
	return file_goquorum_proto_rawDescGZIP(), []int{21}
}

func (x *CheckResult) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CheckResult) GetLatencyMs() int64 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

func (x *CheckResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *CheckResult) GetPeersActive() int32 {
	if x != nil {
		return x.PeersActive
	}
	return 0
}

func (x *CheckResult) GetPeersTotal() int32 {
	if x != nil {
		return x.PeersTotal
	}
	return 0
}

func (x *CheckResult) GetFreeBytes() int64 {
	if x != nil {
		return x.FreeBytes
	}
	return 0
}

func (x *CheckResult) GetTotalBytes() int64 {
	if x != nil {
		return x.TotalBytes
	}
	return 0
}

type ClusterInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClusterInfoRequest) Reset() {
	*x = ClusterInfoRequest{}
	mi := &file_goquorum_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterInfoRequest) ProtoMessage() {}

func (x *ClusterInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_goquorum_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterInfoRequest.ProtoReflect.Descriptor instead.
func (*ClusterInfoRequest) Descriptor() ([]byte, []int) {
	return file_goquorum_proto_rawDescGZIP(), []int{22}
}

type ClusterInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Peers         []*PeerInfo            `protobuf:"bytes,2,rep,name=peers,proto3" json:"peers,omitempty"`
	ClusterStatus ClusterStatus          `protobuf:"varint,3,opt,name=cluster_status,json=clusterStatus,proto3,enum=goquorum.v1.ClusterStatus" json:"cluster_status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClusterInfoResponse) Reset() {
	*x = ClusterInfoResponse{}
	mi := &file_goquorum_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterInfoResponse) ProtoMessage() {}

func (x *ClusterInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_goquorum_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterInfoResponse.ProtoReflect.Descriptor instead.
func (*ClusterInfoResponse) Descriptor() ([]byte, []int) {
	return file_goquorum_proto_rawDescGZIP(), []int{23}
}

func (x *ClusterInfoResponse) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *ClusterInfoResponse) GetPeers() []*PeerInfo {
	if x != nil {
		return x.Peers
	}
	return nil
}

func (x *ClusterInfoResponse) GetClusterStatus() ClusterStatus {
	if x != nil {
		return x.ClusterStatus
	}
	return ClusterStatus_CLUSTER_UNKNOWN
}

type PeerInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Status        PeerStatus             `protobuf:"varint,3,opt,name=status,proto3,enum=goquorum.v1.PeerStatus" json:"status,omitempty"`
	LastSeenUnix  int64                  `protobuf:"varint,4,opt,name=last_seen_unix,json=lastSeenUnix,proto3" json:"last_seen_unix,omitempty"`
	LatencyMs     int64                  `protobuf:"varint,5,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeerInfo) Reset() {
	*x = PeerInfo{}
	mi := &file_goquorum_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerInfo) ProtoMessage() {}

func (x *PeerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_goquorum_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerInfo.ProtoReflect.Descriptor instead.
func (*PeerInfo) Descriptor() ([]byte, []int) {
	return file_goquorum_proto_rawDescGZIP(), []int{24}
}

func (x *PeerInfo) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *PeerInfo) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *PeerInfo) GetStatus() PeerStatus {
	if x != nil {
		return x.Status
	}
	return PeerStatus_PEER_UNKNOWN
}

func (x *PeerInfo) GetLastSeenUnix() int64 {
	if x != nil {
		return x.LastSeenUnix
	}
	return 0
}

func (x *PeerInfo) GetLatencyMs() int64 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

type GetMetricsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMetricsRequest) Reset() {
	*x = GetMetricsRequest{}
	mi := &file_goquorum_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMetricsRequest) ProtoMessage() {}

func (x *GetMetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_goquorum_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMetricsRequest.ProtoReflect.Descriptor instead.
func (*GetMetricsRequest) Descriptor() ([]byte, []int) {
	return file_goquorum_proto_rawDescGZIP(), []int{25}
}

type GetMetricsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metrics       string                 `protobuf:"bytes,1,opt,name=metrics,proto3" json:"metrics,omitempty"` // Prometheus exposition format
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMetricsResponse) Reset() {
	*x = GetMetricsResponse{}
	mi := &file_goquorum_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMetricsResponse) ProtoMessage() {}

func (x *GetMetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_goquorum_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMetricsResponse.ProtoReflect.Descriptor instead.
func (*GetMetricsResponse) Descriptor() ([]byte, []int) {
	return file_goquorum_proto_rawDescGZIP(), []int{26}
}

func (x *GetMetricsResponse) GetMetrics() string {
	if x != nil {
		return x.Metrics
	}
	return ""
}

type KeyInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           []byte                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyInfoRequest) Reset() {
	*x = KeyInfoRequest{}
	mi := &file_goquorum_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyInfoRequest) ProtoMessage() {}

func (x *KeyInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_goquorum_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyInfoRequest.ProtoReflect.Descriptor instead.
func (*KeyInfoRequest) Descriptor() ([]byte, []int) {
	return file_goquorum_proto_rawDescGZIP(), []int{27}
}

func (x *KeyInfoRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

type KeyInfoResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Key            []byte                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Replicas       []*ReplicaKeyInfo      `protobuf:"bytes,2,rep,name=replicas,proto3" json:"replicas,omitempty"`
	PreferenceList []string               `protobuf:"bytes,3,rep,name=preference_list,json=preferenceList,proto3" json:"preference_list,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *KeyInfoResponse) Reset() {
	*x = KeyInfoResponse{}
	mi := &file_goquorum_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyInfoResponse) ProtoMessage() {}

func (x *KeyInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_goquorum_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyInfoResponse.ProtoReflect.Descriptor instead.
func (*KeyInfoResponse) Descriptor() ([]byte, []int) {
	return file_goquorum_proto_rawDescGZIP(), []int{28}
}

func (x *KeyInfoResponse) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *KeyInfoResponse) GetReplicas() []*ReplicaKeyInfo {
	if x != nil {
		return x.Replicas
	}
	return nil
}

func (x *KeyInfoResponse) GetPreferenceList() []string {
	if x != nil {
		return x.PreferenceList
	}
	return nil
}

type ReplicaKeyInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	HasKey        bool                   `protobuf:"varint,2,opt,name=has_key,json=hasKey,proto3" json:"has_key,omitempty"`
	Siblings      []*SiblingInfo         `protobuf:"bytes,3,rep,name=siblings,proto3" json:"siblings,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplicaKeyInfo) Reset() {
	*x = ReplicaKeyInfo{}
	mi := &file_goquorum_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplicaKeyInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicaKeyInfo) ProtoMessage() {}

func (x *ReplicaKeyInfo) ProtoReflect() protoreflect.Message {
	mi := &file_goquorum_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicaKeyInfo.ProtoReflect.Descriptor instead.
func (*ReplicaKeyInfo) Descriptor() ([]byte, []int) {
	return file_goquorum_proto_rawDescGZIP(), []int{29}
}

func (x *ReplicaKeyInfo) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *ReplicaKeyInfo) GetHasKey() bool {
	if x != nil {
		return x.HasKey
	}
	return false
}

func (x *ReplicaKeyInfo) GetSiblings() []*SiblingInfo {
	if x != nil {
		return x.Siblings
	}
	return nil
}

func (x *ReplicaKeyInfo) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type SiblingInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Context       *Context               `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	ValueSize     uint32                 `protobuf:"varint,3,opt,name=value_size,json=valueSize,proto3" json:"value_size,omitempty"`
	Tombstone     bool                   `protobuf:"varint,4,opt,name=tombstone,proto3" json:"tombstone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SiblingInfo) Reset() {
	*x = SiblingInfo{}
	mi := &file_goquorum_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SiblingInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SiblingInfo) ProtoMessage() {}

func (x *SiblingInfo) ProtoReflect() protoreflect.Message {
	mi := &file_goquorum_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SiblingInfo.ProtoReflect.Descriptor instead.
func (*SiblingInfo) Descriptor() ([]byte, []int) {
	return file_goquorum_proto_rawDescGZIP(), []int{30}
}

func (x *SiblingInfo) GetContext() *Context {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *SiblingInfo) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *SiblingInfo) GetValueSize() uint32 {
	if x != nil {
		return x.ValueSize
	}
	return 0
}

func (x *SiblingInfo) GetTombstone() bool {
	if x != nil {
		return x.Tombstone
	}
	return false
}

type TriggerCompactionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TriggerCompactionRequest) Reset() {
	*x = TriggerCompactionRequest{}
	mi := &file_goquorum_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerCompactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerCompactionRequest) ProtoMessage() {}

func (x *TriggerCompactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_goquorum_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerCompactionRequest.ProtoReflect.Descriptor instead.
func (*TriggerCompactionRequest) Descriptor() ([]byte, []int) {
	return file_goquorum_proto_rawDescGZIP(), []int{31}
}

type TriggerCompactionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Started       bool                   `protobuf:"varint,1,opt,name=started,proto3" json:"started,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TriggerCompactionResponse) Reset() {
	*x = TriggerCompactionResponse{}
	mi := &file_goquorum_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerCompactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerCompactionResponse) ProtoMessage() {}

func (x *TriggerCompactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_goquorum_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerCompactionResponse.ProtoReflect.Descriptor instead.
func (*TriggerCompactionResponse) Descriptor() ([]byte, []int) {
	return file_goquorum_proto_rawDescGZIP(), []int{32}
}

func (x *TriggerCompactionResponse) GetStarted() bool {
	if x != nil {
		return x.Started
	}
	return false
}

func (x *TriggerCompactionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_goquorum_proto protoreflect.FileDescriptor

const file_goquorum_proto_rawDesc = "" +
	"\n" +
	"\x0egoquorum.proto\x12\vgoquorum.v1\x1a\x1cgoogle/api/annotations.proto\"Q\n" +
	"\n" +
	"GetRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key\x121\n" +
	"\aoptions\x18\x02 \x01(\v2\x17.goquorum.v1.GetOptionsR\aoptions\"9\n" +
	"\n" +
	"GetOptions\x12\f\n" +
	"\x01r\x18\x01 \x01(\rR\x01r\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\x02 \x01(\rR\ttimeoutMs\"?\n" +
	"\vGetResponse\x120\n" +
	"\bsiblings\x18\x01 \x03(\v2\x14.goquorum.v1.SiblingR\bsiblings\"\x8b\x01\n" +
	"\aSibling\x12\x14\n" +
	"\x05value\x18\x01 \x01(\fR\x05value\x12.\n" +
	"\acontext\x18\x02 \x01(\v2\x14.goquorum.v1.ContextR\acontext\x12\x1c\n" +
	"\ttombstone\x18\x03 \x01(\bR\ttombstone\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\">\n" +
	"\aContext\x123\n" +
	"\aentries\x18\x01 \x03(\v2\x19.goquorum.v1.ContextEntryR\aentries\"A\n" +
	"\fContextEntry\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x18\n" +
	"\acounter\x18\x02 \x01(\x04R\acounter\"\x97\x01\n" +
	"\n" +
	"PutRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\x12.\n" +
	"\acontext\x18\x03 \x01(\v2\x14.goquorum.v1.ContextR\acontext\x121\n" +
	"\aoptions\x18\x04 \x01(\v2\x17.goquorum.v1.PutOptionsR\aoptions\"Z\n" +
	"\n" +
	"PutOptions\x12\f\n" +
	"\x01w\x18\x01 \x01(\rR\x01w\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\x02 \x01(\rR\ttimeoutMs\x12\x1f\n" +
	"\vttl_seconds\x18\x03 \x01(\x03R\n" +
	"ttlSeconds\"=\n" +
	"\vPutResponse\x12.\n" +
	"\acontext\x18\x01 \x01(\v2\x14.goquorum.v1.ContextR\acontext\"\x87\x01\n" +
	"\rDeleteRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key\x12.\n" +
	"\acontext\x18\x02 \x01(\v2\x14.goquorum.v1.ContextR\acontext\x124\n" +
	"\aoptions\x18\x03 \x01(\v2\x1a.goquorum.v1.DeleteOptionsR\aoptions\"<\n" +
	"\rDeleteOptions\x12\f\n" +
	"\x01w\x18\x01 \x01(\rR\x01w\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\x02 \x01(\rR\ttimeoutMs\"\x10\n" +
	"\x0eDeleteResponse\"X\n" +
	"\x0fBatchGetRequest\x12\x12\n" +
	"\x04keys\x18\x01 \x03(\fR\x04keys\x121\n" +
	"\aoptions\x18\x02 \x01(\v2\x17.goquorum.v1.GetOptionsR\aoptions\"I\n" +
	"\x10BatchGetResponse\x125\n" +
	"\aresults\x18\x01 \x03(\v2\x1b.goquorum.v1.BatchGetResultR\aresults\"j\n" +
	"\x0eBatchGetResult\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key\x120\n" +
	"\bsiblings\x18\x02 \x03(\v2\x14.goquorum.v1.SiblingR\bsiblings\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"u\n" +
	"\x0fBatchPutRequest\x12/\n" +
	"\x05items\x18\x01 \x03(\v2\x19.goquorum.v1.BatchPutItemR\x05items\x121\n" +
	"\aoptions\x18\x02 \x01(\v2\x17.goquorum.v1.PutOptionsR\aoptions\"f\n" +
	"\fBatchPutItem\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\x12.\n" +
	"\acontext\x18\x03 \x01(\v2\x14.goquorum.v1.ContextR\acontext\"I\n" +
	"\x10BatchPutResponse\x125\n" +
	"\aresults\x18\x01 \x03(\v2\x1b.goquorum.v1.BatchPutResultR\aresults\"h\n" +
	"\x0eBatchPutResult\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key\x12.\n" +
	"\acontext\x18\x02 \x01(\v2\x14.goquorum.v1.ContextR\acontext\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"\x0f\n" +
	"\rHealthRequest\"\xb3\x02\n" +
	"\x0eHealthResponse\x121\n" +
	"\x06status\x18\x01 \x01(\x0e2\x19.goquorum.v1.HealthStatusR\x06status\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\tR\x06nodeId\x12%\n" +
	"\x0euptime_seconds\x18\x03 \x01(\x03R\ruptimeSeconds\x12\x18\n" +
	"\aversion\x18\x04 \x01(\tR\aversion\x12?\n" +
	"\x06checks\x18\x05 \x03(\v2'.goquorum.v1.HealthResponse.ChecksEntryR\x06checks\x1aS\n" +
	"\vChecksEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12.\n" +
	"\x05value\x18\x02 \x01(\v2\x18.goquorum.v1.CheckResultR\x05value:\x028\x01\"\xde\x01\n" +
	"\vCheckResult\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"latency_ms\x18\x02 \x01(\x03R\tlatencyMs\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\x12!\n" +
	"\fpeers_active\x18\x04 \x01(\x05R\vpeersActive\x12\x1f\n" +
	"\vpeers_total\x18\x05 \x01(\x05R\n" +
	"peersTotal\x12\x1d\n" +
	"\n" +
	"free_bytes\x18\x06 \x01(\x03R\tfreeBytes\x12\x1f\n" +
	"\vtotal_bytes\x18\a \x01(\x03R\n" +
	"totalBytes\"\x14\n" +
	"\x12ClusterInfoRequest\"\x9e\x01\n" +
	"\x13ClusterInfoResponse\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12+\n" +
	"\x05peers\x18\x02 \x03(\v2\x15.goquorum.v1.PeerInfoR\x05peers\x12A\n" +
	"\x0ecluster_status\x18\x03 \x01(\x0e2\x1a.goquorum.v1.ClusterStatusR\rclusterStatus\"\xb3\x01\n" +
	"\bPeerInfo\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12/\n" +
	"\x06status\x18\x03 \x01(\x0e2\x17.goquorum.v1.PeerStatusR\x06status\x12$\n" +
	"\x0elast_seen_unix\x18\x04 \x01(\x03R\flastSeenUnix\x12\x1d\n" +
	"\n" +
	"latency_ms\x18\x05 \x01(\x03R\tlatencyMs\"\x13\n" +
	"\x11GetMetricsRequest\".\n" +
	"\x12GetMetricsResponse\x12\x18\n" +
	"\ametrics\x18\x01 \x01(\tR\ametrics\"\"\n" +
	"\x0eKeyInfoRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key\"\x85\x01\n" +
	"\x0fKeyInfoResponse\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key\x127\n" +
	"\breplicas\x18\x02 \x03(\v2\x1b.goquorum.v1.ReplicaKeyInfoR\breplicas\x12'\n" +
	"\x0fpreference_list\x18\x03 \x03(\tR\x0epreferenceList\"\x8e\x01\n" +
	"\x0eReplicaKeyInfo\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x17\n" +
	"\ahas_key\x18\x02 \x01(\bR\x06hasKey\x124\n" +
	"\bsiblings\x18\x03 \x03(\v2\x18.goquorum.v1.SiblingInfoR\bsiblings\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"\x98\x01\n" +
	"\vSiblingInfo\x12.\n" +
	"\acontext\x18\x01 \x01(\v2\x14.goquorum.v1.ContextR\acontext\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x12\x1d\n" +
	"\n" +
	"value_size\x18\x03 \x01(\rR\tvalueSize\x12\x1c\n" +
	"\ttombstone\x18\x04 \x01(\bR\ttombstone\"\x1a\n" +
	"\x18TriggerCompactionRequest\"O\n" +
	"\x19TriggerCompactionResponse\x12\x18\n" +
	"\astarted\x18\x01 \x01(\bR\astarted\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage*a\n" +
	"\fHealthStatus\x12\x12\n" +
	"\x0eHEALTH_UNKNOWN\x10\x00\x12\x12\n" +
	"\x0eHEALTH_HEALTHY\x10\x01\x12\x13\n" +
	"\x0fHEALTH_DEGRADED\x10\x02\x12\x14\n" +
	"\x10HEALTH_UNHEALTHY\x10\x03*R\n" +
	"\n" +
	"PeerStatus\x12\x10\n" +
	"\fPEER_UNKNOWN\x10\x00\x12\x0f\n" +
	"\vPEER_ACTIVE\x10\x01\x12\x10\n" +
	"\fPEER_SUSPECT\x10\x02\x12\x0f\n" +
	"\vPEER_FAILED\x10\x03*e\n" +
	"\rClusterStatus\x12\x13\n" +
	"\x0fCLUSTER_UNKNOWN\x10\x00\x12\x13\n" +
	"\x0fCLUSTER_HEALTHY\x10\x01\x12\x14\n" +
	"\x10CLUSTER_DEGRADED\x10\x02\x12\x14\n" +
	"\x10CLUSTER_CRITICAL\x10\x032\xd2\x03\n" +
	"\bGoQuorum\x12P\n" +
	"\x03Get\x12\x17.goquorum.v1.GetRequest\x1a\x18.goquorum.v1.GetResponse\"\x16\x82\xd3\xe4\x93\x02\x10\x12\x0e/v1/keys/{key}\x12S\n" +
	"\x03Put\x12\x17.goquorum.v1.PutRequest\x1a\x18.goquorum.v1.PutResponse\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*\x1a\x0e/v1/keys/{key}\x12Y\n" +
	"\x06Delete\x12\x1a.goquorum.v1.DeleteRequest\x1a\x1b.goquorum.v1.DeleteResponse\"\x16\x82\xd3\xe4\x93\x02\x10*\x0e/v1/keys/{key}\x12a\n" +
	"\bBatchGet\x12\x1c.goquorum.v1.BatchGetRequest\x1a\x1d.goquorum.v1.BatchGetResponse\"\x18\x82\xd3\xe4\x93\x02\x12:\x01*\"\r/v1/batch/get\x12a\n" +
	"\bBatchPut\x12\x1c.goquorum.v1.BatchPutRequest\x1a\x1d.goquorum.v1.BatchPutResponse\"\x18\x82\xd3\xe4\x93\x02\x12:\x01*\"\r/v1/batch/put2\xaa\x04\n" +
	"\rGoQuorumAdmin\x12[\n" +
	"\x06Health\x12\x1a.goquorum.v1.HealthRequest\x1a\x1b.goquorum.v1.HealthResponse\"\x18\x82\xd3\xe4\x93\x02\x12\x12\x10/v1/admin/health\x12k\n" +
	"\vClusterInfo\x12\x1f.goquorum.v1.ClusterInfoRequest\x1a .goquorum.v1.ClusterInfoResponse\"\x19\x82\xd3\xe4\x93\x02\x13\x12\x11/v1/admin/cluster\x12h\n" +
	"\n" +
	"GetMetrics\x12\x1e.goquorum.v1.GetMetricsRequest\x1a\x1f.goquorum.v1.GetMetricsResponse\"\x19\x82\xd3\xe4\x93\x02\x13\x12\x11/v1/admin/metrics\x12b\n" +
	"\aKeyInfo\x12\x1b.goquorum.v1.KeyInfoRequest\x1a\x1c.goquorum.v1.KeyInfoResponse\"\x1c\x82\xd3\xe4\x93\x02\x16\x12\x14/v1/admin/keys/{key}\x12\x80\x01\n" +
	"\x11TriggerCompaction\x12%.goquorum.v1.TriggerCompactionRequest\x1a&.goquorum.v1.TriggerCompactionResponse\"\x1c\x82\xd3\xe4\x93\x02\x16\"\x14/v1/admin/compactionB\x11Z\x0fGoQuorum/api;v1b\x06proto3"

var (
	file_goquorum_proto_rawDescOnce sync.Once
	file_goquorum_proto_rawDescData []byte
)

func file_goquorum_proto_rawDescGZIP() []byte {
	file_goquorum_proto_rawDescOnce.Do(func() {
		file_goquorum_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_goquorum_proto_rawDesc), len(file_goquorum_proto_rawDesc)))
	})
	return file_goquorum_proto_rawDescData
}

var file_goquorum_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_goquorum_proto_msgTypes = make([]protoimpl.MessageInfo, 34)
var file_goquorum_proto_goTypes = []any{
	(HealthStatus)(0),                 // 0: goquorum.v1.HealthStatus
	(PeerStatus)(0),                   // 1: goquorum.v1.PeerStatus
	(ClusterStatus)(0),                // 2: goquorum.v1.ClusterStatus
	(*GetRequest)(nil),                // 3: goquorum.v1.GetRequest
	(*GetOptions)(nil),                // 4: goquorum.v1.GetOptions
	(*GetResponse)(nil),               // 5: goquorum.v1.GetResponse
	(*Sibling)(nil),                   // 6: goquorum.v1.Sibling
	(*Context)(nil),                   // 7: goquorum.v1.Context
	(*ContextEntry)(nil),              // 8: goquorum.v1.ContextEntry
	(*PutRequest)(nil),                // 9: goquorum.v1.PutRequest
	(*PutOptions)(nil),                // 10: goquorum.v1.PutOptions
	(*PutResponse)(nil),               // 11: goquorum.v1.PutResponse
	(*DeleteRequest)(nil),             // 12: goquorum.v1.DeleteRequest
	(*DeleteOptions)(nil),             // 13: goquorum.v1.DeleteOptions
	(*DeleteResponse)(nil),            // 14: goquorum.v1.DeleteResponse
	(*BatchGetRequest)(nil),           // 15: goquorum.v1.BatchGetRequest
	(*BatchGetResponse)(nil),          // 16: goquorum.v1.BatchGetResponse
	(*BatchGetResult)(nil),            // 17: goquorum.v1.BatchGetResult
	(*BatchPutRequest)(nil),           // 18: goquorum.v1.BatchPutRequest
	(*BatchPutItem)(nil),              // 19: goquorum.v1.BatchPutItem
	(*BatchPutResponse)(nil),          // 20: goquorum.v1.BatchPutResponse
	(*BatchPutResult)(nil),            // 21: goquorum.v1.BatchPutResult
	(*HealthRequest)(nil),             // 22: goquorum.v1.HealthRequest
	(*HealthResponse)(nil),            // 23: goquorum.v1.HealthResponse
	(*CheckResult)(nil),               // 24: goquorum.v1.CheckResult
	(*ClusterInfoRequest)(nil),        // 25: goquorum.v1.ClusterInfoRequest
	(*ClusterInfoResponse)(nil),       // 26: goquorum.v1.ClusterInfoResponse
	(*PeerInfo)(nil),                  // 27: goquorum.v1.PeerInfo
	(*GetMetricsRequest)(nil),         // 28: goquorum.v1.GetMetricsRequest
	(*GetMetricsResponse)(nil),        // 29: goquorum.v1.GetMetricsResponse
	(*KeyInfoRequest)(nil),            // 30: goquorum.v1.KeyInfoRequest
	(*KeyInfoResponse)(nil),           // 31: goquorum.v1.KeyInfoResponse
	(*ReplicaKeyInfo)(nil),            // 32: goquorum.v1.ReplicaKeyInfo
	(*SiblingInfo)(nil),               // 33: goquorum.v1.SiblingInfo
	(*TriggerCompactionRequest)(nil),  // 34: goquorum.v1.TriggerCompactionRequest
	(*TriggerCompactionResponse)(nil), // 35: goquorum.v1.TriggerCompactionResponse
	nil,                               // 36: goquorum.v1.HealthResponse.ChecksEntry
}
var file_goquorum_proto_depIdxs = []int32{
	4,  // 0: goquorum.v1.GetRequest.options:type_name -> goquorum.v1.GetOptions
	6,  // 1: goquorum.v1.GetResponse.siblings:type_name -> goquorum.v1.Sibling
	7,  // 2: goquorum.v1.Sibling.context:type_name -> goquorum.v1.Context
	8,  // 3: goquorum.v1.Context.entries:type_name -> goquorum.v1.ContextEntry
	7,  // 4: goquorum.v1.PutRequest.context:type_name -> goquorum.v1.Context
	10, // 5: goquorum.v1.PutRequest.options:type_name -> goquorum.v1.PutOptions
	7,  // 6: goquorum.v1.PutResponse.context:type_name -> goquorum.v1.Context
	7,  // 7: goquorum.v1.DeleteRequest.context:type_name -> goquorum.v1.Context
	13, // 8: goquorum.v1.DeleteRequest.options:type_name -> goquorum.v1.DeleteOptions
	4,  // 9: goquorum.v1.BatchGetRequest.options:type_name -> goquorum.v1.GetOptions
	17, // 10: goquorum.v1.BatchGetResponse.results:type_name -> goquorum.v1.BatchGetResult
	6,  // 11: goquorum.v1.BatchGetResult.siblings:type_name -> goquorum.v1.Sibling
	19, // 12: goquorum.v1.BatchPutRequest.items:type_name -> goquorum.v1.BatchPutItem
	10, // 13: goquorum.v1.BatchPutRequest.options:type_name -> goquorum.v1.PutOptions
	7,  // 14: goquorum.v1.BatchPutItem.context:type_name -> goquorum.v1.Context
	21, // 15: goquorum.v1.BatchPutResponse.results:type_name -> goquorum.v1.BatchPutResult
	7,  // 16: goquorum.v1.BatchPutResult.context:type_name -> goquorum.v1.Context
	0,  // 17: goquorum.v1.HealthResponse.status:type_name -> goquorum.v1.HealthStatus
	36, // 18: goquorum.v1.HealthResponse.checks:type_name -> goquorum.v1.HealthResponse.ChecksEntry
	27, // 19: goquorum.v1.ClusterInfoResponse.peers:type_name -> goquorum.v1.PeerInfo
	2,  // 20: goquorum.v1.ClusterInfoResponse.cluster_status:type_name -> goquorum.v1.ClusterStatus
	1,  // 21: goquorum.v1.PeerInfo.status:type_name -> goquorum.v1.PeerStatus
	32, // 22: goquorum.v1.KeyInfoResponse.replicas:type_name -> goquorum.v1.ReplicaKeyInfo
	33, // 23: goquorum.v1.ReplicaKeyInfo.siblings:type_name -> goquorum.v1.SiblingInfo
	7,  // 24: goquorum.v1.SiblingInfo.context:type_name -> goquorum.v1.Context
	24, // 25: goquorum.v1.HealthResponse.ChecksEntry.value:type_name -> goquorum.v1.CheckResult
	3,  // 26: goquorum.v1.GoQuorum.Get:input_type -> goquorum.v1.GetRequest
	9,  // 27: goquorum.v1.GoQuorum.Put:input_type -> goquorum.v1.PutRequest
	12, // 28: goquorum.v1.GoQuorum.Delete:input_type -> goquorum.v1.DeleteRequest
	15, // 29: goquorum.v1.GoQuorum.BatchGet:input_type -> goquorum.v1.BatchGetRequest
	18, // 30: goquorum.v1.GoQuorum.BatchPut:input_type -> goquorum.v1.BatchPutRequest
	22, // 31: goquorum.v1.GoQuorumAdmin.Health:input_type -> goquorum.v1.HealthRequest
	25, // 32: goquorum.v1.GoQuorumAdmin.ClusterInfo:input_type -> goquorum.v1.ClusterInfoRequest
	28, // 33: goquorum.v1.GoQuorumAdmin.GetMetrics:input_type -> goquorum.v1.GetMetricsRequest
	30, // 34: goquorum.v1.GoQuorumAdmin.KeyInfo:input_type -> goquorum.v1.KeyInfoRequest
	34, // 35: goquorum.v1.GoQuorumAdmin.TriggerCompaction:input_type -> goquorum.v1.TriggerCompactionRequest
	5,  // 36: goquorum.v1.GoQuorum.Get:output_type -> goquorum.v1.GetResponse
	11, // 37: goquorum.v1.GoQuorum.Put:output_type -> goquorum.v1.PutResponse
	14, // 38: goquorum.v1.GoQuorum.Delete:output_type -> goquorum.v1.DeleteResponse
	16, // 39: goquorum.v1.GoQuorum.BatchGet:output_type -> goquorum.v1.BatchGetResponse
	20, // 40: goquorum.v1.GoQuorum.BatchPut:output_type -> goquorum.v1.BatchPutResponse
	23, // 41: goquorum.v1.GoQuorumAdmin.Health:output_type -> goquorum.v1.HealthResponse
	26, // 42: goquorum.v1.GoQuorumAdmin.ClusterInfo:output_type -> goquorum.v1.ClusterInfoResponse
	29, // 43: goquorum.v1.GoQuorumAdmin.GetMetrics:output_type -> goquorum.v1.GetMetricsResponse
	31, // 44: goquorum.v1.GoQuorumAdmin.KeyInfo:output_type -> goquorum.v1.KeyInfoResponse
	35, // 45: goquorum.v1.GoQuorumAdmin.TriggerCompaction:output_type -> goquorum.v1.TriggerCompactionResponse
	36, // [36:46] is the sub-list for method output_type
	26, // [26:36] is the sub-list for method input_type
	26, // [26:26] is the sub-list for extension type_name
	26, // [26:26] is the sub-list for extension extendee
	0,  // [0:26] is the sub-list for field type_name
}

func init() { file_goquorum_proto_init() }
func file_goquorum_proto_init() {
	if File_goquorum_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_goquorum_proto_rawDesc), len(file_goquorum_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   34,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_goquorum_proto_goTypes,
		DependencyIndexes: file_goquorum_proto_depIdxs,
		EnumInfos:         file_goquorum_proto_enumTypes,
		MessageInfos:      file_goquorum_proto_msgTypes,
	}.Build()
	File_goquorum_proto = out.File
	file_goquorum_proto_goTypes = nil
	file_goquorum_proto_depIdxs = nil
}
